# Generated by Django 6.1.1 on 2026-09-28 07:17

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extras", "0144_customfield_status"),
        ("ipam", "0097_merge_ipaddress_host_index_and_multi_protocol_services"),
        ("tenancy", "0027_fix_ltree_cascade_triggers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArpEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("mac", models.CharField(max_length=17)),
                ("device", models.CharField(max_length=100)),
                ("interface", models.CharField(blank=True, max_length=100)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip", "last_seen"], name="netbox_ip_r_ip_a188cd_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ip", "mac", "device"),
                        name="netbox_ip_request_arp_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MacEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("mac", models.CharField(max_length=17)),
                ("device", models.CharField(max_length=100)),
                ("port", models.CharField(max_length=100)),
                ("vlan", models.CharField(blank=True, max_length=50)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mac", "device", "port"),
                        name="netbox_ip_request_mac_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Discrepancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("ip", models.GenericIPAddressField()),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "대장 불일치",
                "verbose_name_plural": "대장 불일치",
                "ordering": ("resolved", "-pk"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved", False)),
                        fields=("kind", "ip"),
                        name="netbox_ip_request_open_disc",
                    )
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IPRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("requester", models.CharField(max_length=100)),
                ("mac", models.CharField(blank=True, max_length=17, null=True)),
                ("hostname", models.CharField(blank=True, max_length=100)),
                ("purpose", models.CharField(max_length=200)),
                ("period_days", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(default="submitted", max_length=20)),
                ("approver", models.CharField(blank=True, max_length=100)),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "ip_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "prefix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP 발급 신청",
                "ordering": ("-pk",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["submitted", "approved"]),
                            ("mac__isnull", False),
                        ),
                        fields=("mac",),
                        name="netbox_ip_request_open_mac",
                    )
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
